trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Checkout the repository
  - task: Checkout@1
    displayName: 'Checkout code'

  # Step 2: Set up Node.js
  - task: UseNode@1
    displayName: 'Set up Node.js'
    inputs:
      version: '16' # Use the Node.js version your project requires

  # Step 3: Install dependencies
  - script: npm install
    displayName: 'Install dependencies'

  # Step 4: Build the project
  - script: npm run build
    displayName: 'Build the project'

  # Step 5: Pulumi deployments - Trigger Pulumi Preview
  - script: |
      curl -X POST "https://api.pulumi.com/api/stacks/aenetworks/cicd-pipeline-test/dev/deployments" \
        -H "Authorization: token $(PULUMI_ACCESS_TOKEN)" \
        -H "Content-Type: application/json" \
        -d "$(jq -n --arg stackName "$(STACK_NAME)" \
              '{
                "operation": "preview",
                "operationContext": {
                  "preRunCommands": [
                    "pulumi stack select \($stackName)", 
                    "pulumi config refresh --force"
                  ]
                }
              }')"
    displayName: 'Trigger Pulumi Preview'

  # Step 6: Pulumi deployments - Trigger Pulumi Up
  - script: |
      curl -X POST "https://api.pulumi.com/api/stacks/aenetworks/cicd-pipeline-test/dev/deployments" \
        -H "Authorization: token $(PULUMI_ACCESS_TOKEN)" \
        -H "Content-Type: application/json" \
        -d "$(jq -n --arg stackName "$(STACK_NAME)" \
              '{
                "operation": "update",
                "operationContext": {
                  "preRunCommands": [
                    "pulumi stack select \($stackName)",
                    "pulumi config refresh --force"
                  ]
                }
              }')"
    displayName: 'Trigger Pulumi Up'

# if jq is not working due to it not being installed we can add an additional step to the pipeline to install 
# something similar like "sudo apt-get install jq" or "sudo apt-get install -y jq"